///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTriangleTest
{
    public partial class CoordinateInput
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.

          	string filePath;
          	filePath=System.AppDomain.CurrentDomain.BaseDirectory + @"..\..\CoordinateData.txt";
            string[] lines = File.ReadAllLines(filePath, System.Text.Encoding.Default);
			if (lines != null) {
            	string [] t;
            	foreach(string line in lines){
            		t=line.Split('\t');
            		DataInput(t[0],t[1],t[2],t[3],t[4],t[5]);
            	}
			}
         
        }
        
        
        private void DataInput(string valX_A, string valY_A, string valX_B, string valY_B, string valX_C,string valY_C){
    
            repo.TriangleSettings.LineEditBY.TextValue=valY_B;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditAX.Click("57;15");
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditAX.TextValue=valX_A;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditAY.Click("64;18");
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditAY.TextValue=valY_A;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditBX.Click("54;15");
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditBX.TextValue=valX_B;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditCX.Click("58;14");
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditCX.TextValue=valX_C;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditCY.Click("58;19");
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.LineEditCY.TextValue=valY_C;
            Delay.Milliseconds(0);
            
            repo.TriangleSettings.Построить.Click("30;10");
            Delay.Milliseconds(0);
            
            repo.Triangle.Закрыть.Click("20;5");
            Delay.Milliseconds(0);
        }

    }
}
