///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTriangleTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTriangleTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("826225ea-a75b-4905-ae46-f5af047afc60")]
    public partial class MyTriangleTestRepository : RepoGenBaseFolder
    {
        static MyTriangleTestRepository instance = new MyTriangleTestRepository();
        MyTriangleTestRepositoryFolders.TriangleSettingsAppFolder _trianglesettings;
        MyTriangleTestRepositoryFolders.TriangleAppFolder _triangle;

        /// <summary>
        /// Gets the singleton class instance representing the MyTriangleTestRepository element repository.
        /// </summary>
        [RepositoryFolder("826225ea-a75b-4905-ae46-f5af047afc60")]
        public static MyTriangleTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTriangleTestRepository() 
            : base("MyTriangleTestRepository", "/", null, 0, false, "826225ea-a75b-4905-ae46-f5af047afc60", ".\\RepositoryImages\\MyTriangleTestRepository826225ea.rximgres")
        {
            _trianglesettings = new MyTriangleTestRepositoryFolders.TriangleSettingsAppFolder(this);
            _triangle = new MyTriangleTestRepositoryFolders.TriangleAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("826225ea-a75b-4905-ae46-f5af047afc60")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The TriangleSettings folder.
        /// </summary>
        [RepositoryFolder("c505e6bf-3886-4a97-8ede-30357f23f9dc")]
        public virtual MyTriangleTestRepositoryFolders.TriangleSettingsAppFolder TriangleSettings
        {
            get { return _trianglesettings; }
        }

        /// <summary>
        /// The Triangle folder.
        /// </summary>
        [RepositoryFolder("d0263f62-d80c-4828-af0f-7fde1586522c")]
        public virtual MyTriangleTestRepositoryFolders.TriangleAppFolder Triangle
        {
            get { return _triangle; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTriangleTestRepositoryFolders
    {
        /// <summary>
        /// The TriangleSettingsAppFolder folder.
        /// </summary>
        [RepositoryFolder("c505e6bf-3886-4a97-8ede-30357f23f9dc")]
        public partial class TriangleSettingsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lineeditaxInfo;
            RepoItemInfo _lineeditayInfo;
            RepoItemInfo _lineeditbxInfo;
            RepoItemInfo _lineeditbyInfo;
            RepoItemInfo _lineeditcxInfo;
            RepoItemInfo _lineeditcyInfo;
            RepoItemInfo _построитьInfo;

            /// <summary>
            /// Creates a new TriangleSettings  folder.
            /// </summary>
            public TriangleSettingsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TriangleSettings", "/form[@name='TriangleSettings']", parentFolder, 30000, null, true, "c505e6bf-3886-4a97-8ede-30357f23f9dc", "")
            {
                _lineeditaxInfo = new RepoItemInfo(this, "LineEditAX", "?/?/text[@name='lineEditAX']", 30000, null, "bab5f829-c673-4dd6-86eb-db76af848048");
                _lineeditayInfo = new RepoItemInfo(this, "LineEditAY", "?/?/text[@name='lineEditAY']", 30000, null, "493ff3d3-e674-4aa0-a7cd-6e7d1b619dc2");
                _lineeditbxInfo = new RepoItemInfo(this, "LineEditBX", "?/?/text[@name='lineEditBX']", 30000, null, "4296cbc4-dce6-4cda-b521-aa1ddad506a4");
                _lineeditbyInfo = new RepoItemInfo(this, "LineEditBY", "?/?/text[@name='lineEditBY']", 30000, null, "01627d39-ddec-4cdc-acc4-582e011f819d");
                _lineeditcxInfo = new RepoItemInfo(this, "LineEditCX", "?/?/text[@name='lineEditCX']", 30000, null, "ebb5353f-8217-48ee-badc-89a1acc2c80a");
                _lineeditcyInfo = new RepoItemInfo(this, "LineEditCY", "?/?/text[@name='lineEditCY']", 30000, null, "e346023d-f180-403b-968a-e6f8fdde1435");
                _построитьInfo = new RepoItemInfo(this, "Построить", "button[@text='Построить']", 30000, null, "a6cd4e5a-50dc-4f9d-af0a-1673db4811b7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c505e6bf-3886-4a97-8ede-30357f23f9dc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c505e6bf-3886-4a97-8ede-30357f23f9dc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LineEditAX item.
            /// </summary>
            [RepositoryItem("bab5f829-c673-4dd6-86eb-db76af848048")]
            public virtual Ranorex.Text LineEditAX
            {
                get
                {
                    return _lineeditaxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditAX item info.
            /// </summary>
            [RepositoryItemInfo("bab5f829-c673-4dd6-86eb-db76af848048")]
            public virtual RepoItemInfo LineEditAXInfo
            {
                get
                {
                    return _lineeditaxInfo;
                }
            }

            /// <summary>
            /// The LineEditAY item.
            /// </summary>
            [RepositoryItem("493ff3d3-e674-4aa0-a7cd-6e7d1b619dc2")]
            public virtual Ranorex.Text LineEditAY
            {
                get
                {
                    return _lineeditayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditAY item info.
            /// </summary>
            [RepositoryItemInfo("493ff3d3-e674-4aa0-a7cd-6e7d1b619dc2")]
            public virtual RepoItemInfo LineEditAYInfo
            {
                get
                {
                    return _lineeditayInfo;
                }
            }

            /// <summary>
            /// The LineEditBX item.
            /// </summary>
            [RepositoryItem("4296cbc4-dce6-4cda-b521-aa1ddad506a4")]
            public virtual Ranorex.Text LineEditBX
            {
                get
                {
                    return _lineeditbxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditBX item info.
            /// </summary>
            [RepositoryItemInfo("4296cbc4-dce6-4cda-b521-aa1ddad506a4")]
            public virtual RepoItemInfo LineEditBXInfo
            {
                get
                {
                    return _lineeditbxInfo;
                }
            }

            /// <summary>
            /// The LineEditBY item.
            /// </summary>
            [RepositoryItem("01627d39-ddec-4cdc-acc4-582e011f819d")]
            public virtual Ranorex.Text LineEditBY
            {
                get
                {
                    return _lineeditbyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditBY item info.
            /// </summary>
            [RepositoryItemInfo("01627d39-ddec-4cdc-acc4-582e011f819d")]
            public virtual RepoItemInfo LineEditBYInfo
            {
                get
                {
                    return _lineeditbyInfo;
                }
            }

            /// <summary>
            /// The LineEditCX item.
            /// </summary>
            [RepositoryItem("ebb5353f-8217-48ee-badc-89a1acc2c80a")]
            public virtual Ranorex.Text LineEditCX
            {
                get
                {
                    return _lineeditcxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditCX item info.
            /// </summary>
            [RepositoryItemInfo("ebb5353f-8217-48ee-badc-89a1acc2c80a")]
            public virtual RepoItemInfo LineEditCXInfo
            {
                get
                {
                    return _lineeditcxInfo;
                }
            }

            /// <summary>
            /// The LineEditCY item.
            /// </summary>
            [RepositoryItem("e346023d-f180-403b-968a-e6f8fdde1435")]
            public virtual Ranorex.Text LineEditCY
            {
                get
                {
                    return _lineeditcyInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LineEditCY item info.
            /// </summary>
            [RepositoryItemInfo("e346023d-f180-403b-968a-e6f8fdde1435")]
            public virtual RepoItemInfo LineEditCYInfo
            {
                get
                {
                    return _lineeditcyInfo;
                }
            }

            /// <summary>
            /// The Построить item.
            /// </summary>
            [RepositoryItem("a6cd4e5a-50dc-4f9d-af0a-1673db4811b7")]
            public virtual Ranorex.Button Построить
            {
                get
                {
                    return _построитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Построить item info.
            /// </summary>
            [RepositoryItemInfo("a6cd4e5a-50dc-4f9d-af0a-1673db4811b7")]
            public virtual RepoItemInfo ПостроитьInfo
            {
                get
                {
                    return _построитьInfo;
                }
            }
        }

        /// <summary>
        /// The TriangleAppFolder folder.
        /// </summary>
        [RepositoryFolder("d0263f62-d80c-4828-af0f-7fde1586522c")]
        public partial class TriangleAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new Triangle  folder.
            /// </summary>
            public TriangleAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Triangle", "/form[@title='Triangle']", parentFolder, 30000, null, true, "d0263f62-d80c-4828-af0f-7fde1586522c", "")
            {
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/button[@accessiblename='Закрыть']", 30000, null, "f167657c-8588-4cbe-8cfd-85a3693bf78e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d0263f62-d80c-4828-af0f-7fde1586522c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0263f62-d80c-4828-af0f-7fde1586522c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("f167657c-8588-4cbe-8cfd-85a3693bf78e")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("f167657c-8588-4cbe-8cfd-85a3693bf78e")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
